parent_cfg: configs/dtu_pretrain.yaml

train_dataset_module: datasets.dataloader.llff
test_dataset_module: datasets.dataloader.llff


mvs:
    num_depth: [36, 8]

nerf:
    max_num_samples: 3
    is_adaptive: True
    reweighting: True

train_dataset:
    data_root: 'nerf_llff_data' #
    split: 'train'
    input_h_w: [640, 960]

test_dataset:
    data_root: 'nerf_llff_data' #
    split: 'test'
    input_h_w: [640, 960]

test:
    sampler_meta:
        input_views_num: [3]
    eval_center: True
